Repository jahirfiquitiva/Frames, pull requests merged in 2020-07, with the labels that each got.

#179 New Crowdin updates
  library/src/main/res/values-it-rIT/translatable_strings.xml
  library/src/main/res/values-pl-rPL/translatable_strings.xml
Labels: Status: Needs Info, Status: Stale

#182 Update Contributor Details: Lumiq
  library/src/main/kotlin/dev/jahir/frames/ui/activities/AboutActivity.kt
  library/src/main/res/values/translatable_strings.xml
Labels: Priority: Low

#180 New Crowdin updates
  library/src/main/res/values-hi-rIN/translatable_strings.xml
Labels: Priority: Low, Status: Accepted, Type: Enhancement

#183 New Crowdin updates
  library/src/main/res/values-cs-rCZ/translatable_strings.xml
  library/src/main/res/values-nl-rNL/translatable_strings.xml
Labels: Status: Needs Info, Status: Stale

#184 Revise Text for Muzei Integration Settings
  library/src/main/kotlin/dev/jahir/frames/ui/activities/MuzeiSettingsActivity.kt
  library/src/main/res/layout/activity_muzei_settings.xml
  library/src/main/res/values/translatable_strings.xml
Labels: Priority: Low, Status: Needs Info

#186 New Crowdin updates
  library/src/main/res/values-cs-rCZ/translatable_strings.xml
Labels: Status: Needs Info

#187 New Crowdin updates
  library/src/main/res/values-nl-rNL/translatable_strings.xml
Labels: Status: Needs Info

#189 ‘Refresh on Wi-Fi Only’: Replace Checkbox with Switch
  library/src/main/kotlin/dev/jahir/frames/ui/activities/MuzeiSettingsActivity.kt
  library/src/main/res/layout/activity_muzei_settings.xml
Labels: Status: Pending
